# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.8.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/relaxedrhodes: 2d5c9c29f2573a9e280da68114048a19f80389c30bb057f976c31124839ed81a
  creationTimestamp: "2026-06-18T03:52:50Z"
  labels:
    app: pdm-golang-pod
  name: pdm-golang-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: localhost/pdm-golang:latest
    name: relaxedrhodes
    ports:
    - containerPort: 80
      hostPort: 8081
    tty: true

